### ISSUE TITLE
Monster Hunter World wiki plugin 

### ISSUE THREAD

**Issue by TeKNiK6** [DuckBoss/JJMumbleBot#119]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
To access the monster hunter world wiki and print the first table of the page ex. https://monsterhunterworld.wiki.fextralife.com/Great+Jagras and print the link to the page

**Describe alternatives you've considered**
None yet.

**Additional context**
![image](https://user-images.githubusercontent.com/52848733/61167991-c4ba8d80-a514-11e9-96f4-a3ac624aca30.png)

**Comment by DuckBoss** [comment]
I'll add this feature to the v2.4.0 milestone release.
