### ISSUE TITLE
[Feature request] Text-to-speech

### ISSUE THREAD

**Issue by bamtan** [DuckBoss/JJMumbleBot#120]
**Is your feature request related to a problem? Please describe.**
No :-)

**Describe the solution you'd like**
A text-to-speech command using Streamlabs TTS API (which has multiple voices).

e.g. `!tts <voice> <text>`

**Describe alternatives you've considered**
There is the inbuilt Mumble text-to-speech, but that is client-sided and has limited voice overs.

**Additional context**
API POST command for TTS:

```bash
curl 'https://streamlabs.com/polly/speak' -H 'Accept: application/json' -H 'Content-Type: application/json' --data-binary '{"text":"this is a test one two","voice":"Brian"}' --compressed
```

The response leads to an escaped OGG file format URL.

Available voices:
```
Brian, Ivy, Justin, Russell, Nicole, Emma, Amy, Joanna, Salli, Kimberly, Kendra, Joey, Mizuki, Chantal, Mathieu, Maxim, Raveena
```

There is a limit to how many characters can be in the request, so far I've gotten up to 550 until it throws me `{"error":"Text length is too long!"}`

More information: https://github.com/petercunha/tts 
https://github.com/petercunha/tts/blob/68f051633172bd7e67d19772245a785104957801/lambda/index.js#L34

Let me know if this is possible 😃

**Comment by DuckBoss** [comment]
Hey! 
Thanks for the suggestion, I will add this to the v2.4.0 milestone.
I'm currently working on overhauling the bot to make it more efficient and extensible so I will add this feature to the queue.

**Comment by DuckBoss** [comment]
note to myself:
- allow saving resulting file into sound board clips.
- allow direct streaming of tts content by converting it to a wav format.

**Comment by bamtan** [comment]
Hey, no problems! I look forward to seeing the v2.4.0 release, thanks for your work 😄

**Comment by DuckBoss** [comment]
I've wrapped up this plugin. I'll be releasing it with the next version. Sorry for the delay!

**Comment by DuckBoss** [comment]
Implemented in https://github.com/DuckBoss/JJMumbleBot/pull/141 PR.
Only a few things left until v3.0.0 release
