### ISSUE TITLE
I can't seem to make any certificate work

### ISSUE THREAD

**Issue by felix91gr** [DuckBoss/JJMumbleBot#198]
I'm trying to run the bot locally, but it doesn't matter how I generate the certificate, it keeps giving me this error:

```
JJMumbleBot Web Service was initialized.
INFO:RuntimeLogging:JJMumbleBot Web Service was initialized.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/felix/Documents/Programming/mumble_fooling_around/JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 114, in run
    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occurred, exit here
  File "/home/felix/Documents/Programming/mumble_fooling_around/JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 142, in connect
    self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile, ssl_version=ssl.PROTOCOL_TLS)
  File "/usr/lib/python3.6/ssl.py", line 1158, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.6/ssl.py", line 750, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:3503)
```

As the FAQ recommends, I've been generating my certificates like this: https://www.mumble.com/support/mumble-creating-a-certificate.php

What might be wrong here?

**Comment by bamtan** [comment]
I think I had a similar issue, can you try generating the certificate through this command?

`openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout jjmumblebot.pem -out jjmumblebot.pem -subj "/CN=jjmumblebot"`  

Otherwise there was a similar issue on #3, maybe the troubleshooting there can help

**Comment by felix91gr** [comment]
OMG that worked!

Thank you so much :)

(PS: the wiki should maybe be updated about this?)

**Comment by DuckBoss** [comment]
I'm very close to a full release of v3.0.0, I will add this when updating the wiki.
Thanks!

**Comment by DuckBoss** [comment]
@bamtan I've added your comment to the quick start guide for v3.0+, thanks for contributing!

https://github.com/DuckBoss/JJMumbleBot/wiki/Quick-Start
