### ISSUE TITLE
!help 'Plugin name' is not working

### ISSUE THREAD

**Issue by ajmandourah** [DuckBoss/JJMumbleBot#219]
Tryied the new version today . still the !help 'plugin'  command is not working for example !help youtube. the log is not showing anything

`
[JJMumbleBot(3.0.7).Command]:Commands Received: [Name-> !help youtube]
[JJMumbleBot(3.0.7).Command]:Commands Received: [Name-> !help youtube]

`
Other than that the !help is working as it should be.

**Comment by DuckBoss** [comment]
Hmm, it seems to be working on all my tests. 

Here are a couple things you can try and let me know about while I look into the issue:

1) Try restarting the bot, if that doesn't fix it then try the other suggestions below.
2) I suggest backing up the internal database in the `JJMumbleBot/cfg` folder and letting the bot regenerate it on the next launch. If that fixes the !help command, I might be able to narrow down the problem.
3) Open up the sqlite database using any database software of your choice (I prefer SQLite DB Browser) and send me a screenshot of the contents of the `plugins/plugin_help/commands` tables.
Or alternatively, you can just privately email me the database to duckboss@kakao.com.
I can inspect the database and hopefully narrow down the issue.

**Comment by ajmandourah** [comment]
I sent you the file. seems like no aliases is registered on the db

**Comment by DuckBoss** [comment]
I was able to replicate the issue. Aliases seem to register fine (even on the db file you sent me).
There is an issue with the !help command, I am looking into it.

**Comment by DuckBoss** [comment]
This should fix your issue: [Release v3.0.9](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v3.0.9)

**Comment by ajmandourah** [comment]
Now its working perfectly thanks. 

Any chance to get the old web interface back? It was really helpful

**Comment by DuckBoss** [comment]
I am working on re-implementing it soon. I didn't want to include the previous one since it was more of a test and poorly implemented 👍 

I'm going to close this issue since it's been resolved.

**Comment by DuckBoss** [comment]
@ajmandourah A basic web interface is implemented in [ Release v3.1.0](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v3.1.0)
