### ISSUE TITLE
Youtube searches with a single result cause a crash 

### ISSUE THREAD

**Issue by MacLemon** [DuckBoss/JJMumbleBot#230]
**Describe the bug**
When searching YouTube and you should only get a single result, the YouTube Search crashes.

**To Reproduce**
1. Message a bot with `!yt IH6C3-GUai8` to search for a video with that specific Video ID.
2. See crashdump in Logs.

**Expected behavior**
When searching for a Video by exact ID, the bot should return just that exact video. 

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS hosting the Bot: FreeBSD 12.1
 - JJMumbleBot 3.1.2 (2307bea21da97be8962901b78d52ac743d5fea92)
 - Python Version: 3.7.7
- youtube_dl-2020.06.16.1
- vlc 3.0.11,4

Python module info:
```
$ pip freeze
asn1crypto==1.3.0
Babel==2.8.0
backports.functools-lru-cache==1.6.1
beautifulsoup4==4.9.0
certifi==2020.6.20
cffi==1.14.0
chardet==3.0.4
cheroot==8.3.0
Click==7.0
configparser==5.0.0
cryptography==2.6.1
evdev==0.8.1
Flask==1.1.2
gevent==20.6.2
greenlet==0.4.16
html5lib==1.0.1
idna==2.9
itsdangerous==0.24
jaraco.functools==3.0.1
Jinja2==2.10.1
lxml==4.5.1
MarkupSafe==1.1.1
more-itertools==8.4.0
olefile==0.46
opuslib==3.0.1
Pillow==7.0.0
protobuf==3.12.2
psutil==5.7.0
pycparser==2.20
pymumble==1.2
pyOpenSSL==19.0.0
PySocks==1.7.1
pytz==2020.1
pyudev==0.22.0
requests==2.23.0
six==1.14.0
soupsieve==1.9
sqlite3==0.0.0
Tkinter==0.0.0
urllib3==1.25.9
webencodings==0.5.1
websockets==8.0.2
Werkzeug==1.0.1
WTForms==2.1
youtube-dl==2020.3.24
zope.event==4.4
zope.interface==5.1.0
```

**Additional context**
Log output:

When searching via `!yt IH6C3-GUai8` which should lead to this youtube Video called [Die beste Fahrstuhlmusik oder entspannende Lounge instrumental Aufzug
](https://www.youtube.com/results?search_query=IH6C3-GUai8&page=)
```
[JJMumbleBot(3.1.2).Command]:Commands Received: [MacLemon -> !yt IH6C3-GUai8]
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "JJMumbleBot/plugins/extensions/youtube/youtube.py", line 233, in process
    YH.all_searches = YM.get_vid_list(search_term)
  File "./JJMumbleBot/plugins/extensions/youtube/utility/youtube_helper.py", line 291, in get_vid_list
    search_dict = {"title": all_searches[i]['title'], 'href': all_searches[i]['href']}
IndexError: list index out of range
```

When trying to search for `!yt Die beste Fahrstuhlmusik`

```
[JJMumbleBot(3.1.2).Command]:Commands Received: [MacLemon -> !yt Die beste Fahrstuhlmusik]
Exception in thread Thread-38:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "JJMumbleBot/plugins/extensions/youtube/youtube.py", line 233, in process
    YH.all_searches = YM.get_vid_list(search_term)
  File "./JJMumbleBot/plugins/extensions/youtube/utility/youtube_helper.py", line 291, in get_vid_list
    search_dict = {"title": all_searches[i]['title'], 'href': all_searches[i]['href']}
IndexError: list index out of range
```

**Comment by DuckBoss** [comment]
Thanks for bringing this issue to my attention, I will work on it soon.

**Comment by DuckBoss** [comment]
I've looked into this and it turns out that youtube completely changed how they handle the data for search queries. I will be using a new dependency package to take care of youtube searches until the youtube-dl package is updated to accomodate this change.
I will post more information about this in the release notes for v3.1.3

**Comment by DuckBoss** [comment]
I've looked into this a lot and it seems that youtube has completely changed how they handle the data for search queries.
This completely breaks the existing methods to retrieve youtube search results. Currently the team at youtube-dl is working on a solution (and has been for ~20 days).
I've looked into alternative packages to use temporarily, but many of them are barely functional.

I've fixed the issue of a single search result causing a crash, but currently I don't think any search results work because of the change in youtube.

**Comment by DuckBoss** [comment]
I've fixed the youtube search issue by modifying a partially working library (<a href="https://github.com/joetats/youtube_search">youtube_search</a>) to fit the needs of this project.
Please update to [v3.1.3]() for the fix.

**Comment by MacLemon** [comment]
I can confirm that 3.1.3 does not crash anymore when searching for Video IDs.
I also do get search results with correct links. I can tell the bot to play a video, it will launch `vlc` and fetch the artwork, show that it is playing, but I don't get any sound playing.

I guess I should open a new issue for that, to keep track of this.

Thanks for fixing the crash!
