### ISSUE TITLE
[Feature Request] PLaying a sound / sound board whenever a user log in

### ISSUE THREAD

**Issue by ajmandourah** [DuckBoss/JJMumbleBot#254]
I just though of such an idea. It would not be hard to implement I guess.

**Comment by DuckBoss** [comment]
Hi, I will add this when I get some time. 
You're right, it shouldn't be hard to implement.

**Comment by DuckBoss** [comment]
I created a new extensive callback system that all plugins can use to directly interface with mumble server events such as receiving audio, messages, user connection/disconnection, etc.

With this system I updated the sound board plugin to be able to play a sound clip when a user joins the server.
This is configurable in the 'sound_board/metadata.ini' file.

You can get these new features in the new release : [v4.1.0 Release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v4.1.0)

**Comment by ajmandourah** [comment]
This is great!
Just one thing, is it possible to set a specific sound for every user.
Like is Bob entered it play sth and if Sarah entered it will sth else

**Comment by DuckBoss** [comment]
Yes, the callback system I made should allow this. Also, please note that since this part of the sound board it will not interrupt if another plugin is using the audio like YouTube.

**Comment by DuckBoss** [comment]
Hi,
I ended up moving the user connection audio feature to a separate plugin called "server_tools". This plugin is mainly focused on administrator/high-privilege users and will be used for server event callbacks.
This means that it is no longer a part of the sound_board plugin, which is for the best.



> This is great!
> Just one thing, is it possible to set a specific sound for every user.
> Like is Bob entered it play sth and if Sarah entered it will sth else

This feature has been implemented in [audio-interface-updates](https://github.com/DuckBoss/JJMumbleBot/tree/audio-interface-updates) branch, and will be released as part of v4.2.0 release.

**Comment by DuckBoss** [comment]
> This is great!
> Just one thing, is it possible to set a specific sound for every user.
> Like is Bob entered it play sth and if Sarah entered it will sth else

Added in [v4.2.0 Release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v4.2.0)

**Comment by ajmandourah** [comment]
I noticed you are experimenting with ffmpeg. Does that mean the bot will download the YouTube video and then play it through ffmpeg or it stream it like with vlc?
I have tried some bots that do the earlier and it take a lot of time to convert the video and download it to the memory.

**Comment by DuckBoss** [comment]
> I noticed you are experimenting with ffmpeg. Does that mean the bot will download the YouTube video and then play it through ffmpeg or it stream it like with vlc?
> I have tried some bots that do the earlier and it take a lot of time to convert the video and download it to the memory.

It will work exactly the same way as it did previously with VLC.
VLC uses the same audio library as FFmpeg so it is still using the same underlying audio library.
The advantage now that I've built a custom media player is that I no longer require VLC's additional playback features so I can switch to a lightweight application like FFmpeg. 
In fact it's so similar that the commands I supply to FFmpeg now are the exact same commands I sent to VLC before.

**Comment by ajmandourah** [comment]
Tried it today. i am getting sudden stops in the youtube links. it will play for around half of the audio then stops. No logs though

**Comment by DuckBoss** [comment]
> Tried it today. i am getting sudden stops in the youtube links. it will play for around half of the audio then stops. No logs though

Could you send me the youtube link you're trying to play.

**Comment by ajmandourah** [comment]
https://youtu.be/0XoLSkcacIE

a nice music too ;)

but its with whatever i played

**Comment by DuckBoss** [comment]
> https://youtu.be/0XoLSkcacIE
> 
> a nice music too ;)
> 
> but its with whatever i played

Thanks I'll check it out.

Could you answer these questions:
- Do the youtube videos always stop half-way through or is it at random time intervals?
- Are you using the !ytsearch command to play videos or !link?
- Could you try setting 'FfmpegRunQuiet' to 'true' in your config.ini and seeing if you're getting any errors from FFmpeg?

**Comment by ajmandourah** [comment]
1- around half way sometime after 2/3 of the video
2- nope, directly as a link like  !link https://youtu.be/0XoLSkcacIE
3I am not getting any ffmpeg msges

**Comment by DuckBoss** [comment]
> 1- around half way sometime after 2/3 of the video
> 2- nope, directly as a link like !link https://youtu.be/0XoLSkcacIE
> 3I am not getting any ffmpeg msges

Okay thanks, I'm looking into it.
Also the Ffmpeg output logging isn't working as I expected, so I will patch that as well.

**Comment by ajmandourah** [comment]
thanks

**Comment by DuckBoss** [comment]
I've made some updates to fix this issue in [v4.2.1 Dev Branch](https://github.com/DuckBoss/JJMumbleBot/tree/dev-4.2.1)
Could you check it out? It shouldn't need any config updates.

**Comment by DuckBoss** [comment]
Pushed the updates here: [v4.2.1 Release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v4.2.1)

**Comment by ajmandourah** [comment]
tried it now

it played smoothly until the end then i noteced an error in the logs. after that links wont play unless you issue a stop command.

```
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:53.16, start: -0.007000, bitrate: 143 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, s16le, to 'pipe:':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s (defaul                                         t)
    Metadata:
      encoder         : Lavc58.35.100 pcm_s16le
[tls @ 0x55b6735bcec0] Error in the pull function.ts/s speed=   1x
[https @ 0x55b6735ba880] Will reconnect at 5013472 in 0 second(s), error=Input/o                                         utput error.
[https @ 0x55b6735ba880] Will reconnect at 5245406 in 0 second(s), error=End of                                          file.
[https @ 0x55b6735ba880] HTTP error 416 Requested range not satisfiable

```

**Comment by ajmandourah** [comment]
now getting these

```
  Metadata:
    encoder         : google/video-file
  Duration: 00:04:53.16, start: -0.007000, bitrate: 143 kb/s
    Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Stream mapping:
  Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, s16le, to 'pipe:':
  Metadata:
    encoder         : Lavf58.20.100
    Stream #0:0(eng): Audio: pcm_s16le, 48000 Hz, stereo, s16, 1536 kb/s (default)
    Metadata:
      encoder         : Lavc58.35.100 pcm_s16le
size=     255kB time=00:00:01.36 bitrate=1535.4kbits/s speed=2.62x
error parsing debug value
debug=0
size=     349kB time=00:00:01.86 bitrate=1535.6kbits/s speed=1.82x
Enter command: <target>|all <time>|-1 <command>[ <argument>]

Parse error, at least 3 arguments were expected, only 1 given in string 'oder         : google/video-file'
debug=1   442kB time=00:00:02.36 bitrate=1535.7kbits/s speed=1.55x
size=    2051kB time=00:00:10.94 bitrate=1535.9kbits/s speed=1.08x
error parsing debug value
debug=0
size=    2149kB time=00:00:11.46 bitrate=1535.9kbits/s speed=1.08x
error parsing debug value
debug=0
size=    2816kB time=00:00:15.02 bitrate=1535.9kbits/s speed=1.06x
Enter command: <target>|all <time>|-1 <command>[ <argument>]

Parse error, at least 3 arguments were expected, only 1 given in string 'm_s16le (native))'
```

**Comment by DuckBoss** [comment]
I will look into this first thing tomorrow.
