### ISSUE TITLE
[Feature Request] Docker support

### ISSUE THREAD

**Issue by kaminascripts** [DuckBoss/JJMumbleBot#258]
What do you think about adding docker support to your project? 

Dockerize JJMumbleBot will ease to test the project in an isolated way and avoid having to install all the things that JJMumbleBot needs (python3, opuslib, vlc, etc). It would also help to reduce human error during setup.

Thanks!

**Comment by DuckBoss** [comment]
Hi!
I looked at dockerizing JJMumbleBot previously but couldn't figure it out.
I'll have another look when I get some time and try it out.

If you know how to create a docker image for this project, could you try it out as well?

**Comment by kaminascripts** [comment]
Coul I have write permissions to create a branch ? 
```
permission to remote: Permission to DuckBoss/JJMumbleBot.git denied to kaminascripts.
```

**Comment by DuckBoss** [comment]
> Coul I have write permissions to create a branch ?
> 
> ```
> remote: Permission to DuckBoss/JJMumbleBot.git denied to kaminascripts.
> ```

You should be able to fork the project and then create whatever branches you want.
After making changes to that branch you can send a pull request.

**Comment by DuckBoss** [comment]
If you need help forking this repository, check out this resource:
[Github Forking A Project - Tutorial](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo)
If you need to know how to send a pull request from your forked project:
[Github Creating A Pull Request From A Fork - Tutorial](https://docs.github.com/en/enterprise/2.16/user/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
