### ISSUE TITLE
[Bug] Image plugin cant post images

### ISSUE THREAD

**Issue by kaminascripts** [DuckBoss/JJMumbleBot#259]
Image plugin cant post any image with `!post`

**Steps to reproduce the behavior:**
Execute this command `!post https://github.githubassets.com/images/modules/open_graph/github-octocat.png`

**Expected behavior**
`!post https://github.githubassets.com/images/modules/open_graph/github-octocat.png` should print the image in mumble client chat window.

**Screenshots**
```
[JJMumbleBot(4.1.0).Command]:Commands Received: [test_user -> !post <a href="https://github.githubassets.com/images/modules/open_graph/github-octocat.png">https://github.githubassets.com/images/modules/open_graph/github-octocat.png</a>]
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "JJMumbleBot/JJMumbleBot/plugins/extensions/images/images.py", line 35, in cmd_post
    IH.download_image_stream(img_url)
  File "JJMumbleBot/JJMumbleBot/lib/helpers/image_helper.py", line 116, in download_image_stream
    img_ext = img_url.rsplit('.', 1)[1]
IndexError: list index out of range
```

Environment:
 - OS: Ubuntu 20.04.1 LTS
 - Version v4.1.0
 - Python 3.8.2 (installed by default with Ubuntu 20.04)

It seems img_url received by the image plugin has html code, not only the image url.

**Comment by DuckBoss** [comment]
Oops, I'll take care of this in the next update.

**Comment by DuckBoss** [comment]
I've applied the fix to the [audio-interface-updates](https://github.com/DuckBoss/JJMumbleBot/tree/audio-interface-updates) branch.

If you're using that branch already you can just copy the `images` plugin folder and overwrite the existing one to apply the fix.
Otherwise you can wait for that development branch to merge with the master branch when I do the v4.2.0 update.

**Comment by kaminascripts** [comment]
Working right now, thank you!
