### ISSUE TITLE
[request] Pass YouTube URL to play

### ISSUE THREAD

**Issue by bamtan** [DuckBoss/JJMumbleBot#26]
**Is your feature request related to a problem? Please describe.**
At the moment, users must search for a track using `!yt <search item>`, then make a selection via `!p <number>`.

**Describe the solution you'd like**
It would be great if you could pass a YouTube URL directly to a single command to play.

**Describe alternatives you've considered**
Perhaps using the `!p` command to play the URL, then changing the existing `!p` command to `!c`(hoose) for choosing which song you want to play when using the YouTube search command.

**Additional context**
I hope this is understandable! Thanks for all the work you've put into this.

**Comment by DuckBoss** [comment]
This should be a simple update, I can do this soon.

**Comment by DuckBoss** [comment]
Please check the latest release : https://github.com/DuckBoss/JJMumbleBot/releases/tag/v1.5.1

I've also fixed a major bug I found with the youtube plugin, so I highly suggest updating to this version.
