### ISSUE TITLE
[Feature Request] Ability to listen to other users in the channel

### ISSUE THREAD

**Issue by ajmandourah** [DuckBoss/JJMumbleBot#267]
This might be difficult depending how you want to implement it. basicly the ability to listen to other users in the server / same channel as the bot through either the web interface or other way. this will be interesting to see in fact as I have never seen another bot implementing it.

**Comment by DuckBoss** [comment]
Hmm... I'll have to think about this one.
It has certain security implications that could be troublesome.
Also, if this was implemented it would only be able to listen to users in the same channel because Mumble does not send audio data to users in other channels (as a security/privacy measure).

**Comment by ajmandourah** [comment]
Well the main idea was to be able to implement some sort of distance connection. Apps in Android and iPhone are really not reliable. So I was thinking implementing such will make me able to be listenning to our discussion and reply in other mean, for my special situation it's whatsapp.

I understand it's a huge privacy breach that's why probably no one have implemented it.

Any ideas that may have a middle solution?

**Comment by DuckBoss** [comment]
I'm going to close this issue as it has been inactive. Please re-open it if you have any questions regarding this topic.
