### ISSUE TITLE
[Feature Request] Web interface for sound board

### ISSUE THREAD

**Issue by Gymnae** [DuckBoss/JJMumbleBot#291]
**Is your feature request related to a problem? Please describe.**
I'd love to really have a soundboard with an easy to use web interface that allows for playing, queuing and uploading sound files. Right now we are using a home made solution, but it's rather inflexible. 

**Describe the solution you'd like**
Web interface for the soundboard plugin part of the current web interface.
Maybe with queuing, statistics and upload functionality 

**Describe alternatives you've considered**
Our home made solution based on a sadly hacked together python solution

**Comment by DuckBoss** [comment]
Are you interested in a web interface that displays all the sound clips available on the interface so you just click the sound you want to play [Like this?](https://www.myinstants.com/categories/sound%20effects/)

I might be able to do that in a couple days once I wrap up my college exams.

**Comment by DuckBoss** [comment]
Hello again!

I've created a sound board web interface which will be released in the v4.3.2 update.
I haven't implemented file uploading as I plan on reworking the web interface at a later date.

**Comment by Gymnae** [comment]
Very cool! I will report back once I got to test it. Right now I can't get the websocket to be proxied correctly via caddy
