### ISSUE TITLE
[Feature Request] Move users

### ISSUE THREAD

**Issue by RVRX** [DuckBoss/JJMumbleBot#296]
A move users plugin would be nice if it is possible to get the bot to move users.

Example:
`!moveuser <username> <channel>`

And also one for mumble's ACL groups:
`!movegroup <groupname> <channel>`

**Comment by RVRX** [comment]
Well I've stared at the code for a few hours and it looks like the first one should be possible easily enough and I might tackle it , but I'm unsure about the move by group. Are there any libraries with a group/ACL API or the like?

**Comment by DuckBoss** [comment]
Hello!

The newest version of pymumble (the library used to interface with mumble in this project) had some updates to incorporate ACL so this might be possible. The bot is currently using a slightly older version, so I will see what I can do.

I will have to look into it sometime next week after I wrap up my final exams in college.
Thanks for your suggestion!

**Comment by DuckBoss** [comment]
Hi @RVRX , I'm adding a <code>!moveuser</code> command to the v5.1.0 update coming soon.
I'll investigate moving entire groups, but for now I'll do the above.

**Comment by DuckBoss** [comment]
Please refer to this checklist I've made which includes some administration features: https://github.com/DuckBoss/JJMumbleBot/issues/325

**Comment by DuckBoss** [comment]
Added administration commands which include moving users in [v5.1.0 release](https://github.com/DuckBoss/JJMumbleBot/releases/tag/v5.1.0)
