### ISSUE TITLE
Having an issue when starting the bot

### ISSUE THREAD

**Issue by ReK2Fernandez** [DuckBoss/JJMumbleBot#3]
```
JJ Mumble Bot Booting...
JJ Mumble Bot Initializing...
User privilege setup complete.

######### Initializing Plugins #########

Images Plugin Initialized.
Bot_Commands Plugin Initialized.
Uptime Plugin Initialized.
Sound_Board Plugin Initialized...
Music Plugin Initialized...
Queue Initialized...
Help Plugin Initialized.

######### Running plugin callback tests #########

Images Plugin self-test callback.
Bot_Commands Plugin self-test callback.
Uptime Plugin self-test callback.
Sound_Board Plugin self-test callback.
Help Plugin self-test callback.
Youtube Plugin self-test callback.
JJ Mumble Bot initialized!

Exception in thread Thread-1:
Traceback (most recent call last):
  File "JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 136, in connect
    self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile, ssl_version=ssl.PROTOCOL_TLS)
AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 114, in run
    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occured, exit here
  File "JJMumbleBot/pymumble/pymumble_py3/mumble.py", line 138, in connect
    self.control_socket = ssl.wrap_socket(std_sock, certfile=self.certfile, keyfile=self.keyfile, ssl_version=ssl.PROTOCOL_TLSv1)
  File "/usr/lib/python3.5/ssl.py", line 1069, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python3.5/ssl.py", line 691, in __init__
    self._context.load_cert_chain(certfile, keyfile)
ssl.SSLError: [SSL] PEM lib (_ssl.c:2846)
```
I did a regular pem file with openssl... what could be wrong?

**Comment by ReK2Fernandez** [comment]
Also our server does not use a login/password ... what do I put on the "password" field?

**Comment by DuckBoss** [comment]
As far as this error is concerned:
 "AttributeError: module 'ssl' has no attribute 'PROTOCOL_TLS".

I've never encountered this error so I did some quick searching around online and found that it doesn't relate to the bot or the pymumble library. I suggest updating your python-ssl version as well as launching the bot with python3 like so: "python3 JJMumbleBot".  Apart from those two corrections, have a look at the example config file in this [repository wiki](https://github.com/DuckBoss/JJMumbleBot/wiki/Quick-Start) to make sure your file paths are correct.

I have not tested the bot on any servers that don't have a password. However, according to the pymumble library it should be as simple as leaving the password field blank like so: 
password = ""

Please let me know if you encounter any further issues.

**Comment by DuckBoss** [comment]
As a side note I will be releasing a new version of the bot that uses INI files for configs instead of python files which will have a few changes to current config format. If you update to this version, some changes will have to be made to your config files. I will be updating the wiki on the changes when I push this update.

**Comment by ReK2Fernandez** [comment]
@DuckBoss thanks, this is on Ubuntu 16.04.6 
```
python3-openssl is already the newest version (17.3.0-1~0+ubuntu16.04.1+certbot+1)
```
this are the openssl options I have

```
python-openssl - Python 2 wrapper around the OpenSSL library
python-openssl-doc - Python wrapper around the OpenSSL library (documentation package)
python-requests - elegant and simple HTTP library for Python2, built for human beings
python3-requests - elegant and simple HTTP library for Python3, built for human beings
python3-openssl - Python 3 wrapper around the OpenSSL library
```
:/

**Comment by DuckBoss** [comment]
I'm sorry I meant for you to check `pip3 install pyOpenSSL` to make sure it's up to date.
I've searched online a lot and I can't seem to find much. 

Apart from the pip command above, I noticed that people fixed PROTOCOL_TLS errors on Ubuntu 16 by updating their openssl version by first updating their repository packages and then installing the newest version of ssl like this:
`sudo apt-get update`
and
`sudo apt-get install openssl`

Unfortunately I'm not an expert on anything openssl related so although these fixes aren't particular to JJMumbleBot or the PyMumble library, I hope it fixes your issues.

**Comment by ReK2Fernandez** [comment]
it was the cert... was using a old command.. thanks for your help.

**Comment by ReK2Fernandez** [comment]
@DuckBoss anyways to change the max video long? is  set to 15 but all the youtube mixxes are 1 hour or so

**Comment by ReK2Fernandez** [comment]
@DuckBoss nevermind I found it on the youtube pluging thanks.. will leave the question just in case someone is looking for the answer.

**Comment by DuckBoss** [comment]
@ReK2Fernandez I'm glad you managed to figure out the certification problem. I have updated the bot to v1.3 which uses a new config system. I will make a quick update to include maximum video lengths so that it isn't hard coded soon.

**Comment by DuckBoss** [comment]
I've added a new issue label for this type of problem so that other users may easily find this if they encounter the same problem.
