### ISSUE TITLE
Change Dockerfile and docker-compose to use environment variables for server ip and server port

### ISSUE THREAD

**Issue by wannesdemeyer** [DuckBoss/JJMumbleBot#322]
**Is your feature request related to a problem? Please describe.**
When I want to run JJMumbleBot in a different container service (podman), I need to change the Dockerfile, as passing the ip and port variables happens in the docker-compose file.

**Describe the solution you'd like**
A Dockerfile that supports env variables for connecting to the mumble server.

**Describe alternatives you've considered**
Manually changing the Dockerfile.

**Additional context**
I've included a Dockerfile that works for me, as an example of what I mean. Here you can change the MUMBLE_IP and MUMBLE_PORT variables to pass to the software.

[dockerfile.zip](https://github.com/DuckBoss/JJMumbleBot/files/5873997/dockerfile.zip)

**Comment by wannesdemeyer** [comment]
I've forked your repo to show the full picture, with a changed docker-compose.yaml as well. In my scenario, the container image is built beforahand and is pulled from for instance DockerHub.

[git repo](https://github.com/wannesdemeyer/JJMumbleBot)

**Comment by DuckBoss** [comment]
Hello!

I'll have to test this out on the [v4.4.0 dev branch](https://github.com/DuckBoss/JJMumbleBot/tree/4.4.0-Update) and let you know how it goes.

I'm still learning Docker, so if I have any questions I'll post it below.
Thanks!

**Comment by DuckBoss** [comment]
Hi, one of the main problems I'm having with running a docker container using the updater docker-compose/docker files is that I'm unable to use launch parameters for the bot since it is running through the shell script. Is there a way to pass launch parameters directly to the shell script where it says: <code>python /app -ip "${MUMBLE_IP}" -port "${MUMBLE_PORT}"</code>?

For example, a typical launch setup would include additional launch parameters like so:
```
-password <server_pass> -username <bot_username> -defaultchannel <default_bot_channel> -superuser <bot_super_user>
```

**Comment by DuckBoss** [comment]
I've managed to find a way to resolve this without touching the docker file
by allowing the bot to use environment variables for connecting to the server like so:

<b>New launch parameter</b>: 
```
-env : Uses the system environment variables MUMBLE_IP, MUMBLE_PORT, MUMBLE_PASS for the server IP/Port/Password
```

<b>Example Usage</b>:
```
# Export the IP/PORT to the environment variables before starting the docker bot.
> export MUMBLE_IP='127.0.0.1'
> export MUMBLE_PORT='9999'
# Start the docker bot and use the '-e' parameter in docker-compose to use the environment variables.
# Use the '-env' parameter in the bot to use the environment variables passed through docker.
> sudo -E docker-compose run -e MUMBLE_IP -e MUMBLE_PORT jjmumblebot -env ...
```

Does this work for you? I tested it on the v4.4.0 branch and it seems to work fine.

**Comment by wannesdemeyer** [comment]
This looks great! Exactly the thing I was looking for.

Would it be possible to accept these environment variables without the flag too? Maybe by looking at the options passed first and if the user didn't pass any IP or port, you could see if there are environment variables present. This way the options passed directly by the user would always take precedence over the environment variables.

**Comment by wannesdemeyer** [comment]
I've made pull request #323 to show what I mean. I've tested this code with the docker_compose.yml I included in the pull request. It works as intended, just like your solution, but without the explicit **-env**.

**Comment by wannesdemeyer** [comment]
I've left the -env variable in the pull request and Line 311 in __main__.py needs to be deleted, I left it in there on accident. Thanks for merging my changes!

**Comment by DuckBoss** [comment]
> I've left the -env variable in the pull request and Line 311 in **main**.py needs to be deleted, I left it in there on accident. Thanks for merging my changes!

I've removed the -env variable and the extra debug print statement in this commit: f30d21e
Thanks for your contributions!
