### ISSUE TITLE
[Question] Change permission levels

### ISSUE THREAD

**Issue by benwallacestock** [DuckBoss/JJMumbleBot#334]
Hi,

I am using docker-compose to deploy JJMumbleBot and I am looking to adjust the permission levels of each command. It seems like you can do this by with the privileges.csv in each plugins folder, but this does not seem to be working with docker. Is the best method to clone the repo, change the values and build ot my own docker image, or am I missing something to get the bot to pick up the new permisions levels. 

The other thing that I have noticed is that the code ties to read them from the ./plugins/core folder, whereas the docker image generares the plugin folders all within ./plugins

Thanks!

**Comment by DuckBoss** [comment]
Hello! I'll look into this problem tomorrow and keep you updated.

Thanks for the report!

**Comment by benwallacestock** [comment]
Thats amazing thank you. For now I can fork and complile myself. But yeah the ability for people to be able ot deploy with dokcer and at runtime load in the permissions levels form the CSV would be great aswell, but doing it via a command is great too.

In terms of the plugin folders, I cant remember exactly where in the code I was looking, but when I deployed using docker, all of the plugin folders were genrated in the /plugins folder, and there is no /plugins/core or /plugins/extensions folder. This was all auto genreted in the volume I passed through to docker so might be something there that is wrong when the bot generates the required folders but not sure.

**Comment by DuckBoss** [comment]
> he ability for people to be able ot deploy with dokcer and at runtime load in the permissions levels form the CSV would be great aswell, but doing it via a command is great too.

Do you know if there's a way to load in files to a docker container when it's running (without a restart)? I could also add a high-permission command to download a `command_privileges.csv` file from a URL if you think that would be helpful for people with more complicated deployments. I'm thinking it would work something like this: `!pullpermissions <URL>` and the database would update the permissions for only the commands listed in the csv file.
What do you think?

> when I deployed using docker, all of the plugin folders were genrated in the /plugins folder, and there is no /plugins/core or /plugins/extensions folder. This was all auto genreted in the volume I passed through to docker so might be something there that is wrong when the bot generates the required folders but not sure.

This definitely seems to be a problem with the Docker setup. I haven't made any updates to the docker files in the repository that would cause this so perhaps it's specific to your docker files from your forked repository?

**Comment by DuckBoss** [comment]
> I could also add an admin/owner-level command to download a command_privileges.csv file from a URL if you think that would be helpful for people with more complicated deployments.

I've just implemented this in the [development-branch](https://github.com/DuckBoss/JJMumbleBot/tree/dev-branch).
You can now import aliases/user privileges/command permissions from a downloaded csv file from a provided URL.

Example:
**aliases**: `!importaliases <url_pointing_to_csv_download>`
**user privileges**: `!importuserprivileges <url_pointing_to_csv_download>`
**command permissions**: `!importpermissions <url_pointing_to_csv_download>`

**Comment by benwallacestock** [comment]
So with docker-compose I have a local folder mounted into the /app/JJMumbleBot/cfg directory and files can be added or edited in this directory and the bot would be able to read it at any point during runtime.

I think what would work best would be in the cfg folder in a similar way to how we currently have a config.ini, we would have a like `custom_permissions.csv ` that would be read in every time the bot starts up. That way you could simply make a change to the csv, restart the bot and have the permissions update. Then we could also add a `/refreshprivilages` command that would do this same process of reading the the csv. If a permissions is not defined in the csv, we could fallback to the default values.

Alternativly, how I initially thought it would work, would be to have a custom_privilages.csv in each different plugin folder and these are read in in a same way, but provides some separation between the different commands for each plugin.

I think the import from URL feature is cool for people that maybe don't have as much access to the filesystem, for exmaple if using straight docker without a mounted volume, but with docker compose it is probably easier to just edit the files in the bot folder.

**Comment by DuckBoss** [comment]
Thanks for the feedback!

In the [development-branch](https://github.com/DuckBoss/JJMumbleBot/tree/dev-branch) right now, imported aliases/privileges/permission csv files are downloaded to a `/JJMumbleBot/cfg/downloads` directory. 

> I think what would work best would be in the cfg folder in a similar way to how we currently have a config.ini, we would have a like custom_permissions.csv that would be read in every time the bot starts up. That way you could simply make a change to the csv, restart the bot and have the permissions update.

Yes, I could do this. This is similar to how the `global_aliases.csv` file works right now for aliases, which allows custom aliases to be manually added in the csv file, so this shouldn't be a difficult addition.

> Then we could also add a /refreshprivilages command that would do this same process of reading the the csv. If a permissions is not defined in the csv, we could fallback to the default values.

This should be fairly simple to implement as well.

<hr>
I'll edit this post once I add it to the [development-branch](https://github.com/DuckBoss/JJMumbleBot/tree/dev-branch)

**Comment by DuckBoss** [comment]
Current updates in the dev-branch:
- global_aliases.csv file renamed to custom_aliases.csv and works similarly to the new custom permissions implementation
- Custom_permissions.csv file implemented (auto-generated if missing)
- Added `!refreshpermissions` command to update command permissions from the custom_permissions.csv file
- Added `!refreshaliases` command to update custom aliases from the custom_aliases.csv file
- Database integrity checking, which only regenerates the aliases/commands like it used to when plugin data has been modified or the bot version has been updated. This would prevent data conflicts and other issues when updating the bots. This can be disabled in the `config.ini` file or with launch parameters: `disableintegritycheck`
- Aliases/user privileges/command permissions can be imported from a remote URL using the `!importaliases/!importuserprivileges/!importpermissions` commands.

**Comment by benwallacestock** [comment]
All of that sounds perfect thank you so much! I guess my next question is, when can it be merged into master so I can just reply using your docker-hub build? I should be able to spend some time testing it this weekend using the dev branch if that is helpful?

**Comment by DuckBoss** [comment]
**I'll try to get it merged by the end of Friday or early Saturday.**
<hr>

I wanted to extend the functionality from the custom aliases/permissions to user privileges as well for users that want to use a `custom_user_privileges.csv` file instead of manually assigning user privileges with the `!setprivileges/!addprivileges` commands. I've already implemented a method of doing this by downloading the csv from a URL, so I'll add the local file method too.

This would also speed up the process for upgrading the bot when major updates happen, since all the permissions/alias/user privileges data can be restored from a newly generated database.

**Comment by DuckBoss** [comment]
Hello! The [development branch](https://github.com/DuckBoss/JJMumbleBot/tree/dev-branch) is now stable for testing if you would like to try it out.
For the list of changes/updates, check the [pull request here](https://github.com/DuckBoss/JJMumbleBot/pull/335)

**Please let me know if you have any questions or run into an issues!**

**Comment by DuckBoss** [comment]
I'm closing this issue since v5.2.0 has released.

**Please feel free to re-open this issue if you have any questions or run into an issue!**
