### ISSUE TITLE
change default permission list

### ISSUE THREAD

**Issue by rhetr** [DuckBoss/JJMumbleBot#338]
is it possible to change the default permissions of users when they are registered? eg i want everyone to automatically be able to search and play youtube songs without having to give them the permissions to do so. or is there a better way of going about this?

**Comment by DuckBoss** [comment]
There are multiple ways, but the easiest method is to change the permissions of those commands specifically.
Like this:
```
(Sets the permission of the command to the lowest level so anyone can use it)
!setpermission 'command_name' 1
```

**Comment by rhetr** [comment]
thanks i will try this and reopen if needed
