### ISSUE TITLE
[Question] where to edit MaxVideoLength

### ISSUE THREAD

**Issue by rhetr** [DuckBoss/JJMumbleBot#342]
where can I set MaxVideoLength? i'm not sure if i'm supposed to make a custom config.ini in the cfg/plugins/media/ folder, if i do it in the cfg/config.ini file or somewhere else.

**Comment by DuckBoss** [comment]
Hi! This is currently configurable in the `metadata.ini` file of the media plugin located in `JJMumbleBot/plugins/extensions/media/`.
All plugin-specific configuration options are currently located within the plugins `metadata.ini` file.
<hr>

I have plans to include an option to override a plugins metadata file in a future release.
The groundwork for this has already been implemented as files can be included in the `cfg/plugins/<plugin_name>` folder to be utilized and modified by the plugin (as seen in the server_tools and web_server plugins).

**Comment by rhetr** [comment]
thanks! the plans you have sound great, especially for a containerized deployment. I'll close this for now since you have already created #348 and #347.
